#!/bin/bash
echo "🚀 DESPLEGAR GPS FUNCIONAL EN SERVIDOR"
echo "======================================"

echo "📋 INSTRUCCIONES PARA EL SERVIDOR:"
echo ""
echo "1. 🔐 Conectarse al servidor:"
echo "   ssh usuario@tu-servidor.com"
echo ""
echo "2. 📁 Ir al directorio del proyecto:"
echo "   cd /ruta/al/proyecto/MultiAndamios"
echo ""
echo "3. 📥 Descargar cambios:"
echo "   git pull origin main"
echo ""
echo "4. 🔄 Reiniciar servicios (si es necesario):"
echo "   sudo systemctl restart gunicorn"
echo "   sudo systemctl restart nginx"
echo ""
echo "5. ✅ Verificar que funciona:"
echo "   - Ve a: https://tu-dominio.com/panel/entregas/seguimiento/17/"
echo "   - Inicia sesión como empleado de recibos"
echo "   - Permite acceso a geolocalización"
echo "   - Haz clic en 'ACTUALIZAR GPS'"
echo ""
echo "🌍 CARACTERÍSTICAS DEL GPS IMPLEMENTADO:"
echo "• ✅ Mapa OpenStreetMap (gratuito, sin API keys)"
echo "• ✅ Geolocalización en tiempo real"
echo "• ✅ Auto-actualización cada 30 segundos"
echo "• ✅ Marcadores de vehículo y destino"
echo "• ✅ Coordenadas guardadas en base de datos"
echo "• ✅ Compatible con todos los navegadores"
echo "• ✅ Funciona en HTTPS"
echo ""
echo "📱 URLS DISPONIBLES:"
echo "• /panel/entregas/panel/ - Panel principal de entregas"
echo "• /panel/entregas/seguimiento/[ID]/ - GPS en tiempo real"
echo "• API: /panel/entregas/api/actualizar-ubicacion/"
echo ""
echo "👥 USUARIOS CON ACCESO:"
echo "• Empleados con rol 'recibos_obra'"
echo "• Administradores con rol 'admin'"
echo ""
echo "🎯 ESTADOS DE ENTREGA CON GPS:"
echo "• 'en_camino' - Auto-actualización activada"
echo "• 'programada' - GPS manual disponible"
echo "• 'entregada' - GPS de solo lectura"
echo ""
echo "🔧 TROUBLESHOOTING:"
echo "• Si no aparece el mapa: Verificar conexión a internet"
echo "• Si no actualiza GPS: Verificar permisos de geolocalización"
echo "• Si error de HTTPS: GPS requiere conexión segura en producción"
echo ""
echo "🎉 ¡GPS FUNCIONAL LISTO PARA USAR!"
