# Generated by Django 5.2.3 on 2025-06-16 05:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_metodo_pago_pedido_ref_pago_and_more'),
        ('productos', '0002_producto_descripcion'),
        ('recibos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reciboobra',
            options={'ordering': ['-fecha_entrega'], 'verbose_name': 'Recibo de Obra', 'verbose_name_plural': 'Recibos de Obra'},
        ),
        migrations.RemoveField(
            model_name='reciboobra',
            name='estado_devolucion',
        ),
        migrations.RemoveField(
            model_name='reciboobra',
            name='fecha',
        ),
        migrations.AddField(
            model_name='reciboobra',
            name='condicion_devolucion',
            field=models.TextField(blank=True, help_text='Estado del equipo al momento de la devolución', null=True),
        ),
        migrations.AddField(
            model_name='reciboobra',
            name='condicion_entrega',
            field=models.TextField(blank=True, default='Equipo en buen estado al momento de la entrega', help_text='Estado del equipo al momento de la entrega'),
        ),
        migrations.AddField(
            model_name='reciboobra',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reciboobra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_USO', 'En Uso'), ('DEVUELTO', 'Devuelto'), ('DANADO', 'Dañado'), ('PERDIDO', 'Perdido')], default='PENDIENTE', max_length=50),
        ),
        migrations.AddField(
            model_name='reciboobra',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reciboobra',
            name='fecha_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reciboobra',
            name='firmado_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reciboobra',
            name='firmado_empleado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reciboobra',
            name='notas_devolucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reciboobra',
            name='notas_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reciboobra',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='reciboobra',
            name='cantidad_vuelta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reciboobra',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos_obra', to='pedidos.pedido'),
        ),
    ]
