# Generated by Django 5.2.3 on 2025-06-16 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_metodo_pago_pedido_ref_pago_and_more'),
        ('recibos', '0002_alter_reciboobra_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciboobra',
            name='cantidad_buen_estado',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de productos devueltos en buen estado'),
        ),
        migrations.AddField(
            model_name='reciboobra',
            name='cantidad_danados',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de productos devueltos con daños'),
        ),
        migrations.AddField(
            model_name='reciboobra',
            name='cantidad_inservibles',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de productos devueltos inservibles'),
        ),
        migrations.AddField(
            model_name='reciboobra',
            name='detalle_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibos_obra', to='pedidos.detallepedido'),
        ),
    ]
