# Generated by Django 5.2.3 on 2025-06-16 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_metodo_pago_pedido_ref_pago_and_more'),
        ('productos', '0003_producto_cantidad_en_renta_and_more'),
        ('recibos', '0003_reciboobra_cantidad_buen_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReciboObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_vuelta', models.PositiveIntegerField(default=0)),
                ('cantidad_buen_estado', models.PositiveIntegerField(default=0)),
                ('cantidad_danados', models.PositiveIntegerField(default=0)),
                ('cantidad_inservibles', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_USO', 'En Uso'), ('DEVUELTO', 'Devuelto'), ('DANADO', 'Dañado'), ('PERDIDO', 'Perdido')], default='PENDIENTE', max_length=50)),
                ('condicion_entrega', models.TextField(blank=True, null=True)),
                ('condicion_devolucion', models.TextField(blank=True, null=True)),
                ('detalle_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_recibos', to='pedidos.detallepedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='recibos.reciboobra')),
            ],
        ),
    ]
