# Generated by Django 5.2.3 on 2025-06-24 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_vuelta', models.PositiveIntegerField(default=0)),
                ('cantidad_buen_estado', models.PositiveIntegerField(default=0, help_text='Cantidad de productos devueltos en buen estado')),
                ('cantidad_danados', models.PositiveIntegerField(default=0, help_text='Cantidad de productos devueltos con daños')),
                ('cantidad_inservibles', models.PositiveIntegerField(default=0, help_text='Cantidad de productos devueltos inservibles')),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_USO', 'En Uso'), ('DEVUELTO', 'Devuelto'), ('DANADO', 'Dañado'), ('PERDIDO', 'Perdido')], default='PENDIENTE', max_length=50)),
                ('notas_entrega', models.TextField(blank=True, null=True)),
                ('notas_devolucion', models.TextField(blank=True, null=True)),
                ('firmado_cliente', models.BooleanField(default=False)),
                ('firmado_empleado', models.BooleanField(default=False)),
                ('condicion_entrega', models.TextField(blank=True, default='Equipo en buen estado al momento de la entrega', help_text='Estado del equipo al momento de la entrega')),
                ('condicion_devolucion', models.TextField(blank=True, help_text='Estado del equipo al momento de la devolución', null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('detalle_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibos_obra', to='pedidos.detallepedido')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos_generados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos_obra', to='pedidos.pedido')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Recibo de Obra',
                'verbose_name_plural': 'Recibos de Obra',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='DetalleReciboObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_vuelta', models.PositiveIntegerField(default=0)),
                ('cantidad_buen_estado', models.PositiveIntegerField(default=0)),
                ('cantidad_danados', models.PositiveIntegerField(default=0)),
                ('cantidad_inservibles', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_USO', 'En Uso'), ('DEVUELTO', 'Devuelto'), ('DANADO', 'Dañado'), ('PERDIDO', 'Perdido')], default='PENDIENTE', max_length=50)),
                ('condicion_entrega', models.TextField(blank=True, null=True)),
                ('condicion_devolucion', models.TextField(blank=True, null=True)),
                ('detalle_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_recibos', to='pedidos.detallepedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='recibos.reciboobra')),
            ],
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id_remision', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
