# Generated by Django 4.2.23 on 2025-06-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallereciboobra',
            options={'verbose_name': 'Detalle de Recibo de Obra', 'verbose_name_plural': 'Detalles de Recibos de Obra'},
        ),
        migrations.RemoveField(
            model_name='detallereciboobra',
            name='condicion_devolucion',
        ),
        migrations.RemoveField(
            model_name='detallereciboobra',
            name='condicion_entrega',
        ),
        migrations.RemoveField(
            model_name='reciboobra',
            name='cantidad_buen_estado',
        ),
        migrations.RemoveField(
            model_name='reciboobra',
            name='cantidad_danados',
        ),
        migrations.RemoveField(
            model_name='reciboobra',
            name='cantidad_inservibles',
        ),
        migrations.RemoveField(
            model_name='reciboobra',
            name='cantidad_solicitada',
        ),
        migrations.RemoveField(
            model_name='reciboobra',
            name='cantidad_vuelta',
        ),
        migrations.RemoveField(
            model_name='reciboobra',
            name='detalle_pedido',
        ),
        migrations.RemoveField(
            model_name='reciboobra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reciboobra',
            name='producto',
        ),
        migrations.AlterField(
            model_name='detallereciboobra',
            name='cantidad_buen_estado',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de productos devueltos en buen estado'),
        ),
        migrations.AlterField(
            model_name='detallereciboobra',
            name='cantidad_danados',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de productos devueltos con daños'),
        ),
        migrations.AlterField(
            model_name='detallereciboobra',
            name='cantidad_inservibles',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de productos devueltos inservibles'),
        ),
    ]
