# Generated by Django 4.2.23 on 2025-06-26 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0002_add_missing_fields'),
        ('recibos', '0005_fix_missing_fields'),
    ]

    operations = [
    ]
