# Generated by Django 4.2.23 on 2025-07-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0006_merge_0002_add_missing_fields_0005_fix_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciboobra',
            name='es_recibo_devolucion',
            field=models.BooleanField(default=False, help_text='Indica si este recibo es para devolución de productos'),
        ),
    ]
