# Generated by Django 5.2.3 on 2025-06-24 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_pedido_general', models.CharField(choices=[('pendiente_pago', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('verificando_pago', 'Verificando Pago'), ('pago_aceptado', 'Pago Aceptado'), ('en_empaque', 'En Proceso de Empaque'), ('en_ruta', 'En Ruta de Entrega'), ('entregado', 'Entregado'), ('en_uso', 'En Uso'), ('programado_devolucion', 'Programado para Devolución'), ('vencido', 'Vencido'), ('recogido', 'Recogido'), ('cancelado', 'Cancelado')], default='pendiente_pago', max_length=30)),
                ('estado_seguimiento', models.CharField(choices=[('pendiente', 'Pendiente de Procesar'), ('empacando', 'Empacando Productos'), ('en_ruta_entrega', 'En Ruta de Entrega'), ('entregado', 'Entregado al Cliente'), ('en_uso', 'En Uso por el Cliente'), ('programado_recoleccion', 'Programado para Recolección'), ('en_ruta_recoleccion', 'En Ruta de Recolección'), ('recolectado', 'Recolectado'), ('completado', 'Completado')], default='pendiente', max_length=30)),
                ('direccion_entrega', models.CharField(default='', max_length=255)),
                ('notas', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_pago', models.CharField(blank=True, help_text='Referencia de pago o número de transacción', max_length=100, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_empaque_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_empaque_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_salida_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('duracion_renta', models.IntegerField(default=1, help_text='Duración de la renta en meses')),
                ('fecha_inicio_renta', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('dias_retraso', models.IntegerField(default=0)),
                ('cargo_extra_retraso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultimo_recordatorio', models.DateTimeField(blank=True, null=True)),
                ('dias_para_recordatorio', models.IntegerField(default=5, help_text='Días antes del vencimiento para enviar recordatorio')),
                ('recordatorios_enviados', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('meses_renta', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
            },
        ),
    ]
