# Generated by Django 5.2.3 on 2025-06-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_limite_pago',
            field=models.DateTimeField(blank=True, help_text='Fecha límite para realizar el pago', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='notificacion_pago_enviada',
            field=models.BooleanField(default=False, help_text='Indica si se envió notificación de recordatorio de pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tiempo_limite_pago',
            field=models.IntegerField(default=24, help_text='Horas permitidas para realizar el pago'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido_general',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('verificando_pago', 'Verificando Pago'), ('pago_aceptado', 'Pago Aceptado'), ('en_empaque', 'En Proceso de Empaque'), ('en_ruta', 'En Ruta de Entrega'), ('entregado', 'Entregado'), ('en_uso', 'En Uso'), ('programado_devolucion', 'Programado para Devolución'), ('vencido', 'Vencido'), ('recogido', 'Recogido'), ('cancelado', 'Cancelado'), ('pago_vencido', 'Pago Vencido')], default='pendiente_pago', max_length=30),
        ),
    ]
