# Generated by Django 5.2.3 on 2025-06-24 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_fecha_limite_pago_and_more'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'verbose_name': 'Detalle de Pedido', 'verbose_name_plural': 'Detalles de Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cargo_extra_retraso',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='dias_para_recordatorio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='dias_retraso',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado_seguimiento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_aceptacion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_devolucion_programada',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_devolucion_real',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_empaque_fin',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_empaque_inicio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_entrega_estimada',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_entrega_real',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_inicio_renta',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_salida_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='notificacion_pago_enviada',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='recordatorios_enviados',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ref_pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tiempo_limite_pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ultimo_recordatorio',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='estado',
            field=models.CharField(default='pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='meses_renta',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='duracion_renta',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido_general',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de Pago'), ('procesando_pago', 'Procesando Pago'), ('pagado', 'Pagado'), ('pago_vencido', 'Pago Vencido'), ('pago_rechazado', 'Pago Rechazado'), ('en_preparacion', 'En Preparación'), ('listo_entrega', 'Listo para Entrega'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente_pago', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_limite_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
