# Generated by Django 5.2.3 on 2025-06-24 19:05

from django.db import migrations
from django.utils import timezone
from datetime import timedelta


def forward_func(apps, schema_editor):
    Pedido = apps.get_model('pedidos', 'Pedido')
    # Update all pedidos that have null fecha_limite_pago
    for pedido in Pedido.objects.filter(fecha_limite_pago__isnull=True):
        pedido.fecha_limite_pago = pedido.fecha + timedelta(hours=24)
        pedido.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_detallepedido_options_alter_pedido_options_and_more'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
