# Generated by Django 5.2.3 on 2025-06-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_costo_transporte_pedido_iva_pedido_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_devolucion_programada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido_general',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de Pago'), ('procesando_pago', 'Procesando Pago'), ('pagado', 'Pagado'), ('pago_vencido', 'Pago Vencido'), ('pago_rechazado', 'Pago Rechazado'), ('en_preparacion', 'En Preparación'), ('listo_entrega', 'Listo para Entrega'), ('entregado', 'Entregado'), ('programado_devolucion', 'Programado para Devolución'), ('cancelado', 'Cancelado')], default='pendiente_pago', max_length=50),
        ),
    ]
