# Generated by Django 4.2.23 on 2025-06-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_fecha_devolucion_programada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='periodo_renta',
            field=models.PositiveIntegerField(default=1, verbose_name='Período de renta'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='tipo_renta',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('semanal', 'Semanal')], default='mensual', max_length=10, verbose_name='Tipo de renta'),
        ),
    ]
