# Generated by Django 4.2.23 on 2025-06-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_data_fix_referencias'),
        ('pedidos', '0008_remove_detallepedido_periodo_renta_and_more'),
    ]

    operations = [
    ]
