# Generated by Django 4.2.23 on 2025-06-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_merge_20250626_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='meses_renta',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='dias_renta',
            field=models.PositiveIntegerField(default=1, verbose_name='Días de renta'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='precio_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por día'),
        ),
    ]
