# Generated by Django 4.2.23 on 2025-07-01 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0011_pedido_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha Programada')),
                ('fecha_inicio_recorrido', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de Recorrido')),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Real')),
                ('direccion_salida', models.CharField(max_length=255, verbose_name='Dirección de Salida')),
                ('direccion_destino', models.CharField(max_length=255, verbose_name='Dirección de Destino')),
                ('latitud_actual', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud_actual', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ultima_actualizacion_gps', models.DateTimeField(blank=True, null=True)),
                ('vehiculo_placa', models.CharField(max_length=10, verbose_name='Placa del Vehículo')),
                ('conductor_nombre', models.CharField(max_length=100, verbose_name='Nombre del Conductor')),
                ('conductor_telefono', models.CharField(max_length=15, verbose_name='Teléfono del Conductor')),
                ('estado_entrega', models.CharField(choices=[('programada', 'Programada'), ('en_camino', 'En Camino'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada'), ('devuelta', 'Devuelta')], default='programada', max_length=20)),
                ('tiempo_estimado_llegada', models.DateTimeField(blank=True, null=True, verbose_name='Tiempo Estimado de Llegada')),
                ('distancia_restante_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('firma_recepcion', models.ImageField(blank=True, null=True, upload_to='firmas_entrega/')),
                ('foto_entrega', models.ImageField(blank=True, null=True, upload_to='fotos_entrega/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empleado de Entrega')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Entrega de Pedido',
                'verbose_name_plural': 'Entregas de Pedidos',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
