# Generated by Django 4.2.23 on 2025-07-01 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0012_auto_20250701_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregapedido',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AddField(
            model_name='entregapedido',
            name='latitud_inicial',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud Inicial'),
        ),
        migrations.AddField(
            model_name='entregapedido',
            name='longitud_inicial',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud Inicial'),
        ),
        migrations.AlterField(
            model_name='entregapedido',
            name='empleado_entrega',
            field=models.ForeignKey(limit_choices_to={'rol': 'recibos_obra'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empleado de Entrega'),
        ),
    ]
