# Generated by Django 4.2.23 on 2025-07-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_alter_devolucionparcial_id_alter_extensionrenta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido_general',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de Pago'), ('procesando_pago', 'Procesando Pago'), ('pagado', 'Pagado'), ('pago_vencido', 'Pago Vencido'), ('pago_rechazado', 'Pago Rechazado'), ('en_preparacion', 'En Preparación'), ('listo_entrega', 'Listo para Entrega'), ('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('recibido', 'Recibido'), ('programado_devolucion', 'Programado para Devolución'), ('cancelado', 'Cancelado'), ('CERRADO', 'Cerrado')], default='pendiente_pago', max_length=50),
        ),
    ]
