# Generated by Django 5.2.3 on 2025-06-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_metodopago_options_metodopago_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='en_proceso_pago',
            field=models.BooleanField(default=False, verbose_name='En proceso de pago'),
        ),
    ]
