# Generated by Django 5.2.3 on 2025-06-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_carritoitem_en_proceso_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='costo_transporte',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo de transporte para este municipio.', max_digits=10),
        ),
    ]
