# Generated by Django 4.2.23 on 2025-06-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_municipio_costo_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Usuario activo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_gestionar_clientes',
            field=models.BooleanField(default=False, verbose_name='Puede gestionar clientes'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_gestionar_inventario',
            field=models.BooleanField(default=False, verbose_name='Puede gestionar inventario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_gestionar_pedidos',
            field=models.BooleanField(default=False, verbose_name='Puede gestionar pedidos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_gestionar_productos',
            field=models.BooleanField(default=False, verbose_name='Puede gestionar productos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_gestionar_recibos',
            field=models.BooleanField(default=False, verbose_name='Puede gestionar recibos de obra'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_procesar_pagos',
            field=models.BooleanField(default=False, verbose_name='Puede procesar pagos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_ver_reportes',
            field=models.BooleanField(default=False, verbose_name='Puede ver reportes'),
        ),
    ]
