# Generated by Django 4.2.23 on 2025-06-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_activo_usuario_puede_gestionar_clientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='periodo_renta',
            field=models.PositiveIntegerField(default=1, verbose_name='Período de renta'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='tipo_renta',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('semanal', 'Semanal')], default='mensual', max_length=10, verbose_name='Tipo de renta'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='meses_renta',
            field=models.PositiveIntegerField(default=1, verbose_name='Meses de renta (legacy)'),
        ),
    ]
