# Generated by Django 4.2.23 on 2025-06-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_carritoitem_periodo_renta_carritoitem_tipo_renta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='meses_renta',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='periodo_renta',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='tipo_renta',
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='dias_renta',
            field=models.PositiveIntegerField(default=1, help_text='Número de días a rentar (debe ser múltiplo de los días mínimos del producto)', verbose_name='Días de renta'),
        ),
    ]
