# Generated by Django 4.2.23 on 2025-08-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_limpiar_clientes_duplicados'),
        ('usuarios', '0007_remove_carritoitem_meses_renta_and_more'),
    ]

    operations = [
    ]
