# Generated by Django 5.2.3 on 2025-06-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_renta', models.CharField(max_length=50)),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('cantidad_reservada', models.PositiveIntegerField(default=0)),
                ('cantidad_en_renta', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
    ]
