# Generated by Django 4.2.23 on 2025-06-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20250625_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_semanal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio semanal'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio mensual'),
        ),
    ]
