# Generated by Django 4.2.23 on 2025-06-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_precio_semanal_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_renta',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('semanal', 'Semanal')], default='mensual', max_length=10, verbose_name='Tipo de renta'),
        ),
    ]
