# Generated by Django 4.2.23 on 2025-06-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_tipo_renta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peso en kilogramos de una unidad del producto', max_digits=8, verbose_name='Peso individual (kg)'),
        ),
    ]
