# Generated by Django 4.2.23 on 2025-06-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_semanal',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_renta',
        ),
        migrations.AddField(
            model_name='producto',
            name='dias_minimos_renta',
            field=models.PositiveIntegerField(default=1, help_text='Número mínimo de días consecutivos que se debe rentar este producto', verbose_name='Días mínimos de renta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_diario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de renta por día en pesos', max_digits=10, verbose_name='Precio por día'),
        ),
    ]
